[workspace]
resolver = "2"
members = [
    "escrow-factory",
    "escrow-dst"
]

[workspace.dependencies]
near-sdk = { version = "5.0.0", features = ["legacy"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"
sha2 = "0.10"
borsh = { version = "1.0", features = ["derive"] }

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true 