name: Deploy Worker
on:
  push:
    branches:
      - main
      - dev/**
      - feature/**
      - preview/**
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.0
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Deploy Worker (Production)
        if: github.ref == 'refs/heads/main'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: kikJ0qrh29HKr1YsTPH4zu5M-8C5lRv8-42P3B0K
          accountId: ff635326d89dc7f0237691048abd1ce8
          workingDirectory: packages/shortcut-auth
          command: deploy --minify
      - name: Deploy Worker (Preview)
        if: github.ref != 'refs/heads/main'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: kikJ0qrh29HKr1YsTPH4zu5M-8C5lRv8-42P3B0K
          accountId: ff635326d89dc7f0237691048abd1ce8
          workingDirectory: packages/shortcut-auth
          command: deploy --minify
      - name: Comment Preview URL
        if: github.ref != 'refs/heads/main'
        uses: actions/github-script@v7
        with:
          script: |
            const branchName = context.ref.replace('refs/heads/', '');
            const previewUrl = `https://${branchName}.shortcut-auth.${context.repo.owner}.workers.dev`;
            console.log(`Preview deployment available at: ${previewUrl}`);
            
            // If this was triggered by a PR, comment the URL
            if (context.payload.pull_request) {
              github.rest.issues.createComment({
                issue_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `🚀 Preview deployment available at: ${previewUrl}`
              });
            }